# Generated by Django 5.2.17 on 2026-10-08 01:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # database/schema.sql usa una restricción EXCLUDE ... USING gist sobre UUID
        # (permisos_recurso), que exige btree_gist. El runner instala schema.sql justo
        # después de migrar, así que habilitamos la extensión aquí, dentro de la app.
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS btree_gist;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('almacenamiento_usado_bytes', models.BigIntegerField(default=0)),
                ('esta_activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'organizaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('limite_almacenamiento_bytes', models.BigIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esta_activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'planes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organizacion_id', models.UUIDField()),
                ('estado', models.CharField(choices=[('ACTIVE', 'Activa'), ('PAST_DUE', 'Pago pendiente'), ('CANCELED', 'Cancelada')], default='ACTIVE', max_length=20)),
                ('intervalo', models.CharField(choices=[('MONTHLY', 'Mensual'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=20)),
                ('periodo_inicio', models.DateTimeField()),
                ('periodo_fin', models.DateTimeField()),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'suscripciones',
                'managed': False,
            },
        ),
    ]
