# Generated by Django 5.2.17 on 2026-10-06 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_anual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('almacenamiento_bytes', models.BigIntegerField(blank=True, null=True)),
                ('es_popular', models.BooleanField(default=False)),
                ('caracteristicas', models.JSONField(blank=True, default=list)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['precio_mensual', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('tipo_facturacion', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=10)),
                ('periodo_inicio', models.DateTimeField()),
                ('periodo_fin', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='subscriptions.plan')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
