# Generated by Django 5.2.17 on 2026-10-09 02:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=50)),
                ('referencia_transaccion', models.CharField(max_length=255)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'historial_pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MiembroOrganizacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organizacion_id', models.UUIDField()),
                ('usuario_id', models.UUIDField()),
                ('nivel_rol', models.SmallIntegerField()),
                ('fecha_union', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'miembros_organizacion',
                'managed': False,
            },
        ),
    ]
