# Generated by Django 5.2.17 on 2026-10-06 04:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('color', models.CharField(default='#2563EB', max_length=7)),
                ('color_fondo', models.CharField(default='#EFF6FF', max_length=7)),
                ('ruta_completa', models.CharField(default='/', max_length=1024)),
                ('en_papelera', models.BooleanField(default=False)),
                ('fecha_papelera', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='storage.folder')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_original', models.CharField(max_length=255)),
                ('clave_s3', models.CharField(max_length=1024, unique=True)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('tipo_mime', models.CharField(blank=True, max_length=255)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('en_papelera', models.BooleanField(default=False)),
                ('fecha_papelera', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos', to='storage.folder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('padre__isnull', False)), fields=('owner', 'padre', 'nombre'), name='unique_subfolder_name'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('padre__isnull', True)), fields=('owner', 'nombre'), name='unique_root_folder_name'),
        ),
    ]
