# Generated by Django 5.2.17 on 2026-10-08 23:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organizacion_id', models.UUIDField(blank=True, db_column='organizacion_id', null=True)),
                ('nombre_original', models.CharField(max_length=255)),
                ('clave_s3', models.CharField(max_length=255, unique=True)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('tipo_mime', models.CharField(max_length=100)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('en_papelera', models.BooleanField(default=False)),
                ('fecha_papelera', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'archivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organizacion_id', models.UUIDField(blank=True, db_column='organizacion_id', null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('ruta_completa', models.TextField(default='/')),
                ('en_papelera', models.BooleanField(default=False)),
                ('fecha_papelera', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'carpetas',
                'managed': False,
            },
        ),
    ]
