# Generated by Django 5.2.17 on 2026-09-25 01:24

import auth_workspaces.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correo_electronico', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(db_column='contrasena_hash', max_length=255)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('palabra_secreta_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_column='esta_activo', default=True)),
                ('date_joined', models.DateTimeField(db_column='fecha_creacion', default=django.utils.timezone.now)),
                ('totp_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
            managers=[
                ('objects', auth_workspaces.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organizacion_id', models.UUIDField(null=True)),
                ('accion', models.CharField(max_length=100)),
                ('ip_origen', models.CharField(max_length=45, null=True)),
                ('detalles', models.JSONField(null=True)),
                ('fecha_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_workspaces.usuario')),
            ],
            options={
                'db_table': 'logs_auditoria',
                'managed': False,
            },
        ),
    ]
